version: '3'

services:
  app:
    container_name: app
    ports: 
      - '3000:3000'
    build:
      context: .docker/node
      dockerfile: Dockerfile
      args: 
        - NODE_ENV:development
    entrypoint: .docker/node/entrypoint.sh
    volumes:
      - .:/home/node/app
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=codelab
  
  db:
    container_name: db
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement='all'
    volumes:
      - '.docker/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
